### ISSUE TITLE
Add ability to bind roles to authenticated users

### ISSUE THREAD

**Issue by jlarfors** [verifa/horizon#20]
Similar to how Kubernetes uses the builtin `system:authenticated` group.

E.g. for the subject in the RoleBinding.

```yaml
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
  ```

Groups like `system:authenticated` should be added to the UserInfo when logging in or creating the session.
